#ifndef FUN_TO_MEM_CONVERTER_INCLUDE
#define FUN_TO_MEM_CONVERTER_INCLUDE

#include "commonlib/traits/function_traits.hpp"
#include "commonlib/traits/macro_practical.hpp"

template<int Arity,typename Signature, typename TClass>
struct fun_to_mem_converter_helper;

#define FUN_TO_MEM_COVERTER_HELPER_STRUCT(n) \
	template<typename Signature,typename TClass> \
	struct fun_to_mem_converter_helper<n,Signature,TClass>

#define FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(n) \
	typedef function_traits<Signature> traits; \
	typedef MEM_FUNCTION_POINTER(typename traits::result_type,TClass,Member_Func_Type,typename traits::arg,n);


FUN_TO_MEM_COVERTER_HELPER_STRUCT(0)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(0)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(1)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(1)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(2)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(2)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(3)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(3)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(4)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(4)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(5)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(5)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(6)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(6)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(7)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(7)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(8)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(8)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(9)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(9)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(10)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(10)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(11)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(11)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(12)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(12)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(13)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(13)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(14)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(14)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(15)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(15)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(16)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(16)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(17)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(17)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(18)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(18)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(19)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(19)
};

FUN_TO_MEM_COVERTER_HELPER_STRUCT(20)
{
	FUN_TO_MEM_COVERTER_HELPER_STRUCT_POINTERTYPE(20)
};

template<typename Signature, typename TClass>
struct fun_to_mem_converter
{
	typedef typename fun_to_mem_converter_helper<function_traits<Signature>::arity, Signature, TClass>::Member_Func_Type Member_Func_Type;
};

#endif