#ifndef FUNCTION_TRAITS_INCLUDE
#define FUNCTION_TRAITS_INCLUDE

#include "commonlib/traits/macro_practical.hpp"

template<typename Function>
struct function_pointer_traits
{
	typedef Function* FunctionP_Type;
	typedef Function  Function_Type;
};

template<typename Function>
struct function_pointer_traits<Function*>
{
	typedef Function* FunctionP_Type;
	typedef Function  Function_Type;
};

template<typename Function> struct function_traits_helper;

#define FUNCTION_TRAITS_HLEPER_TEM_0() template<typename R>
#define FUNCTION_TRAITS_HLEPER_TEM(n) template<typename R,AUTO_REPEAT(typename,T,n)>

#define FUNCTION_TRAITS_HLEPER_STRUCT0() \
	FUNCTION_TRAITS_HLEPER_TEM_0() \
	struct function_traits_helper<FUNCTION_POINTER_TYPE(R,T,0)>

#define FUNCTION_TRAITS_HLEPER_STRUCT(n) \
	FUNCTION_TRAITS_HLEPER_TEM(n) \
struct function_traits_helper<FUNCTION_POINTER_TYPE(R,T,n)>

#define _FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(n,type) typedef T##n arg##n##type; // typedef T1 arg1; typedef T2 arg2;
#define FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(n) _FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(n,)

#define FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(n) enum{arity = n}; typedef R result_type;

FUNCTION_TRAITS_HLEPER_STRUCT0()
{
	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(0);
};

FUNCTION_TRAITS_HLEPER_STRUCT(1)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(1);
};

FUNCTION_TRAITS_HLEPER_STRUCT(2)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(2);
};

FUNCTION_TRAITS_HLEPER_STRUCT(3)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(3);
};

FUNCTION_TRAITS_HLEPER_STRUCT(4)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(4);
};

FUNCTION_TRAITS_HLEPER_STRUCT(5)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(5);
};

FUNCTION_TRAITS_HLEPER_STRUCT(6)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(6);
};

FUNCTION_TRAITS_HLEPER_STRUCT(7)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(7);
};

FUNCTION_TRAITS_HLEPER_STRUCT(8)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(8);
};

FUNCTION_TRAITS_HLEPER_STRUCT(9)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(9);
};

FUNCTION_TRAITS_HLEPER_STRUCT(10)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(10);
};

FUNCTION_TRAITS_HLEPER_STRUCT(11)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(11);
};

FUNCTION_TRAITS_HLEPER_STRUCT(12)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(12);
};

FUNCTION_TRAITS_HLEPER_STRUCT(13)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(13);
};

FUNCTION_TRAITS_HLEPER_STRUCT(14)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(14);
};

FUNCTION_TRAITS_HLEPER_STRUCT(15)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(15);
};

FUNCTION_TRAITS_HLEPER_STRUCT(16)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(16);
};

FUNCTION_TRAITS_HLEPER_STRUCT(17)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(17);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(17);
};

FUNCTION_TRAITS_HLEPER_STRUCT(18)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(17);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(18);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(18);
};

FUNCTION_TRAITS_HLEPER_STRUCT(19)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(17);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(18);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(19);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(19);
};

FUNCTION_TRAITS_HLEPER_STRUCT(20)
{
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(17);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(18);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(19);
	FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(20);

	FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(20);
};

template<typename Function_Type>
struct function_traits : public function_traits_helper<typename function_pointer_traits<Function_Type>::FunctionP_Type>
{
	typedef typename function_pointer_traits<Function_Type>::Function_Type Function_Type;
	typedef typename function_pointer_traits<Function_Type>::FunctionP_Type FunctionP_Type;
};


#endif