#ifndef MFUNCTION_TRAITS_INCLUDE
#define MFUNCTION_TRAITS_INCLUDE

template<typename Function> struct mfunction_traits_helper;

#define MEM_FUNCTION_TRAITS_HLEPER_TEM_0() template<class TClass,typename R>
#define MEM_FUNCTION_TRAITS_HLEPER_TEM(n) template<class TClass,typename R,AUTO_REPEAT(typename,T,n)>

#define MEM_FUNCTION_TRAITS_HLEPER_STRUCT0() \
	MEM_FUNCTION_TRAITS_HLEPER_TEM_0() \
struct mfunction_traits_helper<MEM_FUNCTION_POINTER_TYPE(R,TClass,T,0)>

#define MEM_FUNCTION_TRAITS_HLEPER_STRUCT(n) \
	MEM_FUNCTION_TRAITS_HLEPER_TEM(n) \
struct mfunction_traits_helper<MEM_FUNCTION_POINTER_TYPE(R,TClass,T,n)>

#define _MEM__FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(n,type) typedef T##n arg##n##type;
#define MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(n) _FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(n,)

#define MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(n) enum{arity = n}; typedef R result_type; typedef TClass class_type;

MEM_FUNCTION_TRAITS_HLEPER_STRUCT0()
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(0);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(1)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(1);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(2)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(2);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(3)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(3);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(4)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(4);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(5)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(5);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(6)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(6);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(7)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(7);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(8)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(8);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(9)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(9);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(10)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(10);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(11)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(11);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(12)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(12);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(13)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(13);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(14)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(14);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(15)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(15);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(16)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(16);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(17)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(17);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(17);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(18)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(17);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(18);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(18);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(19)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(17);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(18);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(19);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(19);
};

MEM_FUNCTION_TRAITS_HLEPER_STRUCT(20)
{
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(1);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(2);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(3);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(4);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(5);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(6);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(7);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(8);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(9);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(10);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(11);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(12);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(13);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(14);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(15);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(16);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(17);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(18);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(19);
	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_PARAMTYPE(20);

	MEM_FUNCTION_TRAITS_HLEPER_STRUCT_OTHERTYPE(20);
};


template<typename _MFunctionP_Type>
struct mfunction_traits : public mfunction_traits_helper<_MFunctionP_Type>
{
	typedef _MFunctionP_Type MFunctionP_Type;
};

#endif