cc_library(
	name = 'proto',
	srcs = [
		'src/cmd.pb.cc',
		'src/comm_conf.pb.cc',
		'src/connsvr_config.pb.cc',
		'src/mytest.pb.cc',
		'src/router.pb.cc',
		'src/routersvr_config.pb.cc',
		'src/server_agent_conf.pb.cc',
		'src/server_agent_data.pb.cc',
		'src/svr_base.pb.cc',
		'src/transfer.pb.cc',
		'src/transfersvr.pb.cc',
	],
	deps = [
		'//google:protobuf',
	],
)