cc_binary(
    name = 'connsvr',
    srcs = [
       'main.cpp',
       'conn_svr.cpp',
	   'transaction/trans_application.cpp',
    ],
    deps = [
        '//commonlib:common',
		'//protolib:proto',
		'//slience:slience'
    ],
)
