cc_binary(
    name = 'transfersvr',
    srcs = [
       'main.cpp',
       'transfersvr.cpp',
	   'transaction/trans_application.cpp',
	   'router_inst_mgr.cpp',
	   'transfer_inst_mgr.cpp',
	   'user_login_mgr.cpp',
    ],
    deps = [
        '//commonlib:common',
		'//protolib:proto',
		'//slience:slience'
    ],
)
