cc_binary(
    name = 'server_agent',
    srcs = [
       'main.cpp',
       'server_agent.cpp',
    ],
    deps = [
        '//commonlib:common',
		'//protolib:proto',
		'//slience:slience'
    ],
)
