// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gcm.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Host struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InnerIp              string   `protobuf:"bytes,2,opt,name=inner_ip,json=innerIp,proto3" json:"inner_ip,omitempty"`
	OuterIp              string   `protobuf:"bytes,3,opt,name=outer_ip,json=outerIp,proto3" json:"outer_ip,omitempty"`
	DeployIp             string   `protobuf:"bytes,4,opt,name=deploy_ip,json=deployIp,proto3" json:"deploy_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{0}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetInnerIp() string {
	if m != nil {
		return m.InnerIp
	}
	return ""
}

func (m *Host) GetOuterIp() string {
	if m != nil {
		return m.OuterIp
	}
	return ""
}

func (m *Host) GetDeployIp() string {
	if m != nil {
		return m.DeployIp
	}
	return ""
}

type HostCfg struct {
	Hosts                []*Host  `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostCfg) Reset()         { *m = HostCfg{} }
func (m *HostCfg) String() string { return proto.CompactTextString(m) }
func (*HostCfg) ProtoMessage()    {}
func (*HostCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{1}
}

func (m *HostCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostCfg.Unmarshal(m, b)
}
func (m *HostCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostCfg.Marshal(b, m, deterministic)
}
func (m *HostCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostCfg.Merge(m, src)
}
func (m *HostCfg) XXX_Size() int {
	return xxx_messageInfo_HostCfg.Size(m)
}
func (m *HostCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_HostCfg.DiscardUnknown(m)
}

var xxx_messageInfo_HostCfg proto.InternalMessageInfo

func (m *HostCfg) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type ArtifactFile struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  string   `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	NeedBackup           bool     `protobuf:"varint,4,opt,name=need_backup,json=needBackup,proto3" json:"need_backup,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtifactFile) Reset()         { *m = ArtifactFile{} }
func (m *ArtifactFile) String() string { return proto.CompactTextString(m) }
func (*ArtifactFile) ProtoMessage()    {}
func (*ArtifactFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{2}
}

func (m *ArtifactFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactFile.Unmarshal(m, b)
}
func (m *ArtifactFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactFile.Marshal(b, m, deterministic)
}
func (m *ArtifactFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactFile.Merge(m, src)
}
func (m *ArtifactFile) XXX_Size() int {
	return xxx_messageInfo_ArtifactFile.Size(m)
}
func (m *ArtifactFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactFile.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactFile proto.InternalMessageInfo

func (m *ArtifactFile) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *ArtifactFile) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *ArtifactFile) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *ArtifactFile) GetNeedBackup() bool {
	if m != nil {
		return m.NeedBackup
	}
	return false
}

func (m *ArtifactFile) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AgentArtifact struct {
	Files                []*ArtifactFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FunctionId           int32           `protobuf:"varint,3,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	StartCmd             string          `protobuf:"bytes,4,opt,name=start_cmd,json=startCmd,proto3" json:"start_cmd,omitempty"`
	StopCmd              string          `protobuf:"bytes,5,opt,name=stop_cmd,json=stopCmd,proto3" json:"stop_cmd,omitempty"`
	CleanCmd             string          `protobuf:"bytes,6,opt,name=clean_cmd,json=cleanCmd,proto3" json:"clean_cmd,omitempty"`
	CheckCmd             string          `protobuf:"bytes,7,opt,name=check_cmd,json=checkCmd,proto3" json:"check_cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AgentArtifact) Reset()         { *m = AgentArtifact{} }
func (m *AgentArtifact) String() string { return proto.CompactTextString(m) }
func (*AgentArtifact) ProtoMessage()    {}
func (*AgentArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{3}
}

func (m *AgentArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentArtifact.Unmarshal(m, b)
}
func (m *AgentArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentArtifact.Marshal(b, m, deterministic)
}
func (m *AgentArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentArtifact.Merge(m, src)
}
func (m *AgentArtifact) XXX_Size() int {
	return xxx_messageInfo_AgentArtifact.Size(m)
}
func (m *AgentArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_AgentArtifact proto.InternalMessageInfo

func (m *AgentArtifact) GetFiles() []*ArtifactFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *AgentArtifact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentArtifact) GetFunctionId() int32 {
	if m != nil {
		return m.FunctionId
	}
	return 0
}

func (m *AgentArtifact) GetStartCmd() string {
	if m != nil {
		return m.StartCmd
	}
	return ""
}

func (m *AgentArtifact) GetStopCmd() string {
	if m != nil {
		return m.StopCmd
	}
	return ""
}

func (m *AgentArtifact) GetCleanCmd() string {
	if m != nil {
		return m.CleanCmd
	}
	return ""
}

func (m *AgentArtifact) GetCheckCmd() string {
	if m != nil {
		return m.CheckCmd
	}
	return ""
}

type TemplateArtifactItem struct {
	TemplateName         string          `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Files                []*ArtifactFile `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TemplateArtifactItem) Reset()         { *m = TemplateArtifactItem{} }
func (m *TemplateArtifactItem) String() string { return proto.CompactTextString(m) }
func (*TemplateArtifactItem) ProtoMessage()    {}
func (*TemplateArtifactItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{4}
}

func (m *TemplateArtifactItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateArtifactItem.Unmarshal(m, b)
}
func (m *TemplateArtifactItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateArtifactItem.Marshal(b, m, deterministic)
}
func (m *TemplateArtifactItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateArtifactItem.Merge(m, src)
}
func (m *TemplateArtifactItem) XXX_Size() int {
	return xxx_messageInfo_TemplateArtifactItem.Size(m)
}
func (m *TemplateArtifactItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateArtifactItem.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateArtifactItem proto.InternalMessageInfo

func (m *TemplateArtifactItem) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *TemplateArtifactItem) GetFiles() []*ArtifactFile {
	if m != nil {
		return m.Files
	}
	return nil
}

type TemplateArtifact struct {
	TemplateArtifacts    []*TemplateArtifactItem `protobuf:"bytes,1,rep,name=template_artifacts,json=templateArtifacts,proto3" json:"template_artifacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TemplateArtifact) Reset()         { *m = TemplateArtifact{} }
func (m *TemplateArtifact) String() string { return proto.CompactTextString(m) }
func (*TemplateArtifact) ProtoMessage()    {}
func (*TemplateArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{5}
}

func (m *TemplateArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateArtifact.Unmarshal(m, b)
}
func (m *TemplateArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateArtifact.Marshal(b, m, deterministic)
}
func (m *TemplateArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateArtifact.Merge(m, src)
}
func (m *TemplateArtifact) XXX_Size() int {
	return xxx_messageInfo_TemplateArtifact.Size(m)
}
func (m *TemplateArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateArtifact proto.InternalMessageInfo

func (m *TemplateArtifact) GetTemplateArtifacts() []*TemplateArtifactItem {
	if m != nil {
		return m.TemplateArtifacts
	}
	return nil
}

type NormalArtifactItem struct {
	TemplateName         string          `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FunctionId           int32           `protobuf:"varint,3,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	StartPriority        int32           `protobuf:"varint,4,opt,name=start_priority,json=startPriority,proto3" json:"start_priority,omitempty"`
	Files                []*ArtifactFile `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	Copies               uint32          `protobuf:"varint,6,opt,name=copies,proto3" json:"copies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NormalArtifactItem) Reset()         { *m = NormalArtifactItem{} }
func (m *NormalArtifactItem) String() string { return proto.CompactTextString(m) }
func (*NormalArtifactItem) ProtoMessage()    {}
func (*NormalArtifactItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{6}
}

func (m *NormalArtifactItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NormalArtifactItem.Unmarshal(m, b)
}
func (m *NormalArtifactItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NormalArtifactItem.Marshal(b, m, deterministic)
}
func (m *NormalArtifactItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalArtifactItem.Merge(m, src)
}
func (m *NormalArtifactItem) XXX_Size() int {
	return xxx_messageInfo_NormalArtifactItem.Size(m)
}
func (m *NormalArtifactItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalArtifactItem.DiscardUnknown(m)
}

var xxx_messageInfo_NormalArtifactItem proto.InternalMessageInfo

func (m *NormalArtifactItem) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *NormalArtifactItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NormalArtifactItem) GetFunctionId() int32 {
	if m != nil {
		return m.FunctionId
	}
	return 0
}

func (m *NormalArtifactItem) GetStartPriority() int32 {
	if m != nil {
		return m.StartPriority
	}
	return 0
}

func (m *NormalArtifactItem) GetFiles() []*ArtifactFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *NormalArtifactItem) GetCopies() uint32 {
	if m != nil {
		return m.Copies
	}
	return 0
}

type NormalArtifact struct {
	Artifacts            []*NormalArtifactItem `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NormalArtifact) Reset()         { *m = NormalArtifact{} }
func (m *NormalArtifact) String() string { return proto.CompactTextString(m) }
func (*NormalArtifact) ProtoMessage()    {}
func (*NormalArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{7}
}

func (m *NormalArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NormalArtifact.Unmarshal(m, b)
}
func (m *NormalArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NormalArtifact.Marshal(b, m, deterministic)
}
func (m *NormalArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalArtifact.Merge(m, src)
}
func (m *NormalArtifact) XXX_Size() int {
	return xxx_messageInfo_NormalArtifact.Size(m)
}
func (m *NormalArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_NormalArtifact proto.InternalMessageInfo

func (m *NormalArtifact) GetArtifacts() []*NormalArtifactItem {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

type ArtifactGroupItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArtifactNames        []string `protobuf:"bytes,2,rep,name=artifact_names,json=artifactNames,proto3" json:"artifact_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtifactGroupItem) Reset()         { *m = ArtifactGroupItem{} }
func (m *ArtifactGroupItem) String() string { return proto.CompactTextString(m) }
func (*ArtifactGroupItem) ProtoMessage()    {}
func (*ArtifactGroupItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{8}
}

func (m *ArtifactGroupItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactGroupItem.Unmarshal(m, b)
}
func (m *ArtifactGroupItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactGroupItem.Marshal(b, m, deterministic)
}
func (m *ArtifactGroupItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactGroupItem.Merge(m, src)
}
func (m *ArtifactGroupItem) XXX_Size() int {
	return xxx_messageInfo_ArtifactGroupItem.Size(m)
}
func (m *ArtifactGroupItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactGroupItem.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactGroupItem proto.InternalMessageInfo

func (m *ArtifactGroupItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArtifactGroupItem) GetArtifactNames() []string {
	if m != nil {
		return m.ArtifactNames
	}
	return nil
}

type ArtifactGroup struct {
	ArtifactGroups       []*ArtifactGroupItem `protobuf:"bytes,1,rep,name=artifact_groups,json=artifactGroups,proto3" json:"artifact_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ArtifactGroup) Reset()         { *m = ArtifactGroup{} }
func (m *ArtifactGroup) String() string { return proto.CompactTextString(m) }
func (*ArtifactGroup) ProtoMessage()    {}
func (*ArtifactGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{9}
}

func (m *ArtifactGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactGroup.Unmarshal(m, b)
}
func (m *ArtifactGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactGroup.Marshal(b, m, deterministic)
}
func (m *ArtifactGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactGroup.Merge(m, src)
}
func (m *ArtifactGroup) XXX_Size() int {
	return xxx_messageInfo_ArtifactGroup.Size(m)
}
func (m *ArtifactGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactGroup proto.InternalMessageInfo

func (m *ArtifactGroup) GetArtifactGroups() []*ArtifactGroupItem {
	if m != nil {
		return m.ArtifactGroups
	}
	return nil
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{10}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type InstanceGroup struct {
	ArtifactGroupName    string   `protobuf:"bytes,1,opt,name=artifact_group_name,json=artifactGroupName,proto3" json:"artifact_group_name,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	InstanceId           int32    `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceGroup) Reset()         { *m = InstanceGroup{} }
func (m *InstanceGroup) String() string { return proto.CompactTextString(m) }
func (*InstanceGroup) ProtoMessage()    {}
func (*InstanceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{11}
}

func (m *InstanceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGroup.Unmarshal(m, b)
}
func (m *InstanceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGroup.Marshal(b, m, deterministic)
}
func (m *InstanceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGroup.Merge(m, src)
}
func (m *InstanceGroup) XXX_Size() int {
	return xxx_messageInfo_InstanceGroup.Size(m)
}
func (m *InstanceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGroup proto.InternalMessageInfo

func (m *InstanceGroup) GetArtifactGroupName() string {
	if m != nil {
		return m.ArtifactGroupName
	}
	return ""
}

func (m *InstanceGroup) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *InstanceGroup) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type Zone struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	InstanceGroups       []*InstanceGroup `protobuf:"bytes,4,rep,name=instance_groups,json=instanceGroups,proto3" json:"instance_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{12}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Zone) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Zone) GetInstanceGroups() []*InstanceGroup {
	if m != nil {
		return m.InstanceGroups
	}
	return nil
}

type World struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	User                 string      `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Passwd               string      `protobuf:"bytes,4,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Variables            []*KeyValue `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	Zones                []*Zone     `protobuf:"bytes,6,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *World) Reset()         { *m = World{} }
func (m *World) String() string { return proto.CompactTextString(m) }
func (*World) ProtoMessage()    {}
func (*World) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{13}
}

func (m *World) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_World.Unmarshal(m, b)
}
func (m *World) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_World.Marshal(b, m, deterministic)
}
func (m *World) XXX_Merge(src proto.Message) {
	xxx_messageInfo_World.Merge(m, src)
}
func (m *World) XXX_Size() int {
	return xxx_messageInfo_World.Size(m)
}
func (m *World) XXX_DiscardUnknown() {
	xxx_messageInfo_World.DiscardUnknown(m)
}

var xxx_messageInfo_World proto.InternalMessageInfo

func (m *World) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *World) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *World) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *World) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *World) GetVariables() []*KeyValue {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *World) GetZones() []*Zone {
	if m != nil {
		return m.Zones
	}
	return nil
}

type DeployInfo struct {
	TmpRootPath          string   `protobuf:"bytes,2,opt,name=tmp_root_path,json=tmpRootPath,proto3" json:"tmp_root_path,omitempty"`
	DstRootPath          string   `protobuf:"bytes,3,opt,name=dst_root_path,json=dstRootPath,proto3" json:"dst_root_path,omitempty"`
	ListenPort           int32    `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployInfo) Reset()         { *m = DeployInfo{} }
func (m *DeployInfo) String() string { return proto.CompactTextString(m) }
func (*DeployInfo) ProtoMessage()    {}
func (*DeployInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{14}
}

func (m *DeployInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployInfo.Unmarshal(m, b)
}
func (m *DeployInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployInfo.Marshal(b, m, deterministic)
}
func (m *DeployInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployInfo.Merge(m, src)
}
func (m *DeployInfo) XXX_Size() int {
	return xxx_messageInfo_DeployInfo.Size(m)
}
func (m *DeployInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeployInfo proto.InternalMessageInfo

func (m *DeployInfo) GetTmpRootPath() string {
	if m != nil {
		return m.TmpRootPath
	}
	return ""
}

func (m *DeployInfo) GetDstRootPath() string {
	if m != nil {
		return m.DstRootPath
	}
	return ""
}

func (m *DeployInfo) GetListenPort() int32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

type Deploy struct {
	TmpRootPath          string      `protobuf:"bytes,2,opt,name=tmp_root_path,json=tmpRootPath,proto3" json:"tmp_root_path,omitempty"`
	DstRootPath          string      `protobuf:"bytes,3,opt,name=dst_root_path,json=dstRootPath,proto3" json:"dst_root_path,omitempty"`
	Variables            []*KeyValue `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty"`
	Worlds               []*World    `protobuf:"bytes,5,rep,name=worlds,proto3" json:"worlds,omitempty"`
	ListenPort           int32       `protobuf:"varint,6,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Deploy) Reset()         { *m = Deploy{} }
func (m *Deploy) String() string { return proto.CompactTextString(m) }
func (*Deploy) ProtoMessage()    {}
func (*Deploy) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e49f9b792356f6b, []int{15}
}

func (m *Deploy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy.Unmarshal(m, b)
}
func (m *Deploy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy.Marshal(b, m, deterministic)
}
func (m *Deploy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy.Merge(m, src)
}
func (m *Deploy) XXX_Size() int {
	return xxx_messageInfo_Deploy.Size(m)
}
func (m *Deploy) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy proto.InternalMessageInfo

func (m *Deploy) GetTmpRootPath() string {
	if m != nil {
		return m.TmpRootPath
	}
	return ""
}

func (m *Deploy) GetDstRootPath() string {
	if m != nil {
		return m.DstRootPath
	}
	return ""
}

func (m *Deploy) GetVariables() []*KeyValue {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *Deploy) GetWorlds() []*World {
	if m != nil {
		return m.Worlds
	}
	return nil
}

func (m *Deploy) GetListenPort() int32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

func init() {
	proto.RegisterType((*Host)(nil), "protocol.Host")
	proto.RegisterType((*HostCfg)(nil), "protocol.HostCfg")
	proto.RegisterType((*ArtifactFile)(nil), "protocol.ArtifactFile")
	proto.RegisterType((*AgentArtifact)(nil), "protocol.AgentArtifact")
	proto.RegisterType((*TemplateArtifactItem)(nil), "protocol.TemplateArtifactItem")
	proto.RegisterType((*TemplateArtifact)(nil), "protocol.TemplateArtifact")
	proto.RegisterType((*NormalArtifactItem)(nil), "protocol.NormalArtifactItem")
	proto.RegisterType((*NormalArtifact)(nil), "protocol.NormalArtifact")
	proto.RegisterType((*ArtifactGroupItem)(nil), "protocol.ArtifactGroupItem")
	proto.RegisterType((*ArtifactGroup)(nil), "protocol.ArtifactGroup")
	proto.RegisterType((*KeyValue)(nil), "protocol.KeyValue")
	proto.RegisterType((*InstanceGroup)(nil), "protocol.InstanceGroup")
	proto.RegisterType((*Zone)(nil), "protocol.Zone")
	proto.RegisterType((*World)(nil), "protocol.World")
	proto.RegisterType((*DeployInfo)(nil), "protocol.DeployInfo")
	proto.RegisterType((*Deploy)(nil), "protocol.Deploy")
}

func init() { proto.RegisterFile("gcm.proto", fileDescriptor_6e49f9b792356f6b) }

var fileDescriptor_6e49f9b792356f6b = []byte{
	// 813 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0x23, 0x35,
	0x14, 0x56, 0xd2, 0x4c, 0x9a, 0x39, 0xd9, 0x49, 0xb7, 0x66, 0x59, 0x8a, 0x8a, 0x68, 0x65, 0x58,
	0xb1, 0x17, 0xa8, 0xa0, 0xe5, 0x8e, 0x2b, 0x96, 0x56, 0x40, 0x04, 0x54, 0x95, 0xc5, 0x8f, 0xc4,
	0xcd, 0xc8, 0x9d, 0x71, 0x12, 0x2b, 0x33, 0x63, 0xcb, 0x76, 0x76, 0x15, 0x24, 0x78, 0x25, 0x5e,
	0x84, 0x37, 0xe0, 0x96, 0x07, 0x41, 0xfe, 0x9b, 0x99, 0x64, 0x7b, 0x11, 0x10, 0x57, 0xb5, 0xbf,
	0xef, 0x8c, 0xcf, 0x77, 0xbe, 0x73, 0x7a, 0x02, 0xe9, 0xb2, 0xa8, 0xaf, 0xa4, 0x12, 0x46, 0xa0,
	0x89, 0xfb, 0x53, 0x88, 0x0a, 0xd7, 0x30, 0xfa, 0x46, 0x68, 0x83, 0x10, 0x8c, 0x1a, 0x5a, 0xb3,
	0xb3, 0xc1, 0xe5, 0xe0, 0x79, 0x4a, 0xdc, 0x19, 0xbd, 0x0b, 0x13, 0xde, 0x34, 0x4c, 0xe5, 0x5c,
	0x9e, 0x0d, 0x1d, 0x7e, 0xec, 0xee, 0x73, 0x69, 0x29, 0xb1, 0x31, 0x9e, 0x3a, 0xf2, 0x94, 0xbb,
	0xcf, 0x25, 0x3a, 0x87, 0xb4, 0x64, 0xb2, 0x12, 0x5b, 0xcb, 0x8d, 0x1c, 0x37, 0xf1, 0xc0, 0x5c,
	0xe2, 0x4f, 0xe0, 0xd8, 0xa6, 0xbb, 0x5e, 0x2c, 0xd1, 0x87, 0x90, 0xac, 0x84, 0x36, 0xfa, 0x6c,
	0x70, 0x79, 0xf4, 0x7c, 0xfa, 0x62, 0x76, 0x15, 0x35, 0x5d, 0xd9, 0x08, 0xe2, 0x49, 0xfc, 0x3b,
	0x3c, 0x7a, 0xa9, 0x0c, 0x5f, 0xd0, 0xc2, 0x7c, 0xc5, 0x2b, 0x86, 0x1e, 0xc3, 0x91, 0x56, 0x45,
	0x90, 0x69, 0x8f, 0x16, 0x29, 0xb5, 0x09, 0x02, 0xed, 0x11, 0xbd, 0x0d, 0x63, 0xae, 0xf3, 0x92,
	0x2b, 0x27, 0x6d, 0x42, 0x12, 0xae, 0x6f, 0xb8, 0x42, 0x17, 0x30, 0x6d, 0x18, 0x2b, 0xf3, 0x7b,
	0x5a, 0xac, 0x37, 0x5e, 0xda, 0x84, 0x80, 0x85, 0xbe, 0x74, 0x88, 0xf5, 0xc0, 0xd0, 0xa5, 0x3e,
	0x4b, 0x2e, 0x8f, 0xac, 0x07, 0xf6, 0x8c, 0xff, 0x1e, 0x40, 0xf6, 0x72, 0xc9, 0x1a, 0x13, 0x55,
	0xa0, 0x8f, 0x21, 0x59, 0xf0, 0x8a, 0x45, 0xdd, 0x4f, 0x3b, 0xdd, 0x7d, 0xa1, 0xc4, 0x07, 0xb5,
	0xbe, 0x0e, 0x7b, 0xbe, 0x5e, 0xc0, 0x74, 0xb1, 0x69, 0x0a, 0xc3, 0x45, 0x93, 0xf3, 0xd2, 0x89,
	0x4c, 0x08, 0x44, 0x68, 0x5e, 0x5a, 0x0b, 0xb5, 0xa1, 0xca, 0xe4, 0x45, 0x5d, 0x46, 0x0b, 0x1d,
	0x70, 0x5d, 0x97, 0xd6, 0x7a, 0x6d, 0x84, 0x74, 0x5c, 0xe2, 0xad, 0xb7, 0x77, 0x4b, 0x9d, 0x43,
	0x5a, 0x54, 0x8c, 0x36, 0x8e, 0x1b, 0xfb, 0xef, 0x1c, 0x10, 0xc9, 0x15, 0x2b, 0xd6, 0x8e, 0x3c,
	0x0e, 0xa4, 0x05, 0xae, 0xeb, 0x12, 0x73, 0x78, 0xf2, 0x03, 0xab, 0x65, 0x45, 0x0d, 0x8b, 0x55,
	0xcc, 0x0d, 0xab, 0xd1, 0x07, 0x90, 0x99, 0x80, 0xe7, 0xbd, 0xf9, 0x78, 0x14, 0xc1, 0x5b, 0x5b,
	0x4f, 0xeb, 0xc8, 0xf0, 0x00, 0x47, 0x30, 0x85, 0xc7, 0xfb, 0xa9, 0xd0, 0xf7, 0x80, 0xda, 0x34,
	0x34, 0x80, 0xd1, 0xe0, 0xf7, 0xbb, 0xe7, 0x1e, 0x92, 0x48, 0x4e, 0xcd, 0x1e, 0xaa, 0xf1, 0x5f,
	0x03, 0x40, 0xb7, 0x42, 0xd5, 0xb4, 0xfa, 0xf7, 0xc5, 0xfc, 0xa7, 0x86, 0x3d, 0x83, 0x99, 0x6f,
	0x98, 0x54, 0x5c, 0x28, 0x6e, 0xb6, 0xae, 0x6b, 0x09, 0xc9, 0x1c, 0x7a, 0x17, 0xc0, 0xce, 0xa8,
	0xe4, 0x90, 0xd1, 0x79, 0x0a, 0xe3, 0x42, 0x48, 0xce, 0xb4, 0x6b, 0x65, 0x46, 0xc2, 0x0d, 0x7f,
	0x07, 0xb3, 0xdd, 0xe2, 0xd0, 0xe7, 0x90, 0xee, 0xbb, 0xf6, 0x5e, 0xf7, 0xf6, 0x9b, 0x4e, 0x90,
	0x2e, 0x1c, 0xdf, 0xc2, 0x69, 0xa4, 0xbe, 0x56, 0x62, 0x23, 0x9d, 0x53, 0x0f, 0x6d, 0x83, 0x67,
	0x30, 0x8b, 0x5f, 0x39, 0xf7, 0x7c, 0xbb, 0x53, 0x92, 0x45, 0xd4, 0xda, 0xa7, 0xf1, 0x8f, 0x90,
	0xed, 0xbc, 0x87, 0x6e, 0xe0, 0xa4, 0xfd, 0x6e, 0x69, 0x91, 0x28, 0xf1, 0xfc, 0xcd, 0xf2, 0x5b,
	0x05, 0xa4, 0xcd, 0xe5, 0x20, 0x8d, 0x5f, 0xc0, 0xe4, 0x5b, 0xb6, 0xfd, 0x89, 0x56, 0x1b, 0xb7,
	0x03, 0xd6, 0x6c, 0x1b, 0x77, 0xc0, 0x9a, 0x6d, 0xd1, 0x13, 0x48, 0x5e, 0x59, 0x2a, 0x74, 0xcd,
	0x5f, 0xf0, 0x6f, 0x90, 0xcd, 0x1b, 0x6d, 0x68, 0x53, 0x30, 0x2f, 0xe5, 0x0a, 0xde, 0xda, 0x95,
	0xd2, 0x1f, 0x83, 0xd3, 0x9d, 0x8c, 0x6e, 0x16, 0xce, 0x21, 0xb5, 0x5b, 0x28, 0xef, 0x0d, 0xc4,
	0xc4, 0x02, 0xb7, 0x61, 0x28, 0x78, 0x78, 0xbd, 0x37, 0x14, 0x11, 0x9a, 0x97, 0xb8, 0x82, 0xd1,
	0x2f, 0xa2, 0x61, 0x0f, 0x9a, 0x39, 0x83, 0x21, 0x2f, 0xdd, 0x93, 0x09, 0x19, 0xf2, 0x12, 0x7d,
	0x01, 0x27, 0xed, 0x63, 0xc1, 0xa4, 0x91, 0x33, 0xe9, 0x9d, 0xce, 0xa4, 0x9d, 0x5a, 0xc8, 0x8c,
	0xf7, 0xaf, 0x1a, 0xff, 0x31, 0x80, 0xe4, 0x67, 0xa1, 0xaa, 0xf2, 0xa0, 0x7c, 0x08, 0x46, 0x1b,
	0xcd, 0x54, 0xd8, 0xdd, 0xee, 0x6c, 0xe7, 0x4d, 0x52, 0xad, 0x5f, 0xc7, 0x95, 0x13, 0x6e, 0xe8,
	0x53, 0x48, 0x5f, 0x51, 0xc5, 0xe9, 0x7d, 0x37, 0xb9, 0xa8, 0x53, 0x15, 0xbb, 0x42, 0xba, 0x20,
	0xbb, 0xda, 0x7f, 0x15, 0x8d, 0x1b, 0xdc, 0xbd, 0xd5, 0x6e, 0x0d, 0x21, 0x9e, 0xc4, 0x1b, 0x80,
	0x1b, 0xff, 0xbb, 0xd0, 0x2c, 0x04, 0xc2, 0x90, 0x99, 0x5a, 0xe6, 0x4a, 0x08, 0x93, 0x4b, 0x6a,
	0x56, 0xc1, 0xef, 0xa9, 0xa9, 0x25, 0x11, 0xc2, 0xdc, 0x51, 0xb3, 0xb2, 0x31, 0xa5, 0x36, 0xbd,
	0x18, 0x2f, 0x7f, 0x5a, 0x6a, 0xd3, 0xc6, 0x5c, 0xc0, 0xb4, 0xe2, 0xda, 0xb0, 0x26, 0x97, 0x42,
	0x99, 0xf0, 0x7f, 0x08, 0x1e, 0xba, 0x13, 0xca, 0xe0, 0x3f, 0x07, 0x30, 0xf6, 0x79, 0xff, 0xb7,
	0x9c, 0x3b, 0x0e, 0x8d, 0x0e, 0x71, 0xe8, 0x23, 0x18, 0xbf, 0xb6, 0xcd, 0x8a, 0x86, 0x9e, 0x74,
	0xe1, 0xae, 0x89, 0x24, 0xd0, 0xfb, 0xe5, 0x8c, 0xf7, 0xcb, 0xb9, 0x1f, 0xbb, 0x0f, 0x3f, 0xfb,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x45, 0xd7, 0xb2, 0xde, 0x07, 0x00, 0x00,
}
